data:
  batch_size: 256
  num_workers: 10
  val_ratio: 0.1

optim:
  algo: AdamW
  params:
    lr: 1e-4

nepochs: 300
loss: # "CrossEntropyLoss"
amp: True

logging:
  wandb:
    project: project-name
    entity: project-name
  logdir: # Better to provide the fullpath, especially on the cluster

model:
  class: net

